In [49]:
#70% entrenamiento departamentos
import numpy as np
import pandas as pd
from sklearn import linear_model

dr=pd.read_csv(r"departamentos-pro.csv",dtype="string")

dr['precio'] = dr['precio'].fillna('0')
dr['precio'] = dr['precio'].apply(lambda x: x.replace('$', '').replace(',', '').replace('MN','').replace(' ','')).astype(float)
dr['precio'] = dr['precio'].replace(0,np.NaN)
dr['mets'] = dr['mets'].fillna('0')
dr['mets'] = dr['mets'].astype(float)
dr['mets'] = dr['mets'].replace(0,np.NaN)
model=linear_model.LinearRegression()
depapre=pd.DataFrame(dr.loc[dr['web-scraper-start-url'].str.contains("mirador"),'precio'])
depamet=pd.DataFrame(dr.loc[dr['web-scraper-start-url'].str.contains("mirador"),'mets'])
#print(depapre)100% = 73 70% = 51
depapre=depapre.iloc[0:51]
depamet=depamet.iloc[0:51]
#print(depapre)

model.fit(depamet,depapre)
model.predict(pd.DataFrame([120]))

array([[16245.67080354]])

In [46]:
#30% test deoartamentos
import numpy as np
import pandas as pd
from sklearn import linear_model

dr=pd.read_csv(r"departamentos-pro.csv",dtype="string")

dr['precio'] = dr['precio'].fillna('0')
dr['precio'] = dr['precio'].apply(lambda x: x.replace('$', '').replace(',', '').replace('MN','').replace(' ','')).astype(float)
dr['precio'] = dr['precio'].replace(0,np.NaN)
dr['mets'] = dr['mets'].fillna('0')
dr['mets'] = dr['mets'].astype(float)
dr['mets'] = dr['mets'].replace(0,np.NaN)
model=linear_model.LinearRegression()
depapre=pd.DataFrame(dr.loc[dr['web-scraper-start-url'].str.contains("mirador"),'precio'])
depamet=pd.DataFrame(dr.loc[dr['web-scraper-start-url'].str.contains("mirador"),'mets'])
#print(depapre)100% = 73 70% = 51
depapre=depapre.iloc[51:]
depamet=depamet.iloc[51:]
#print(depapre)

model.fit(depamet,depapre)
model.predict(pd.DataFrame([120]))

array([[13382.30089306]])

In [70]:
#70% entrenamiento casas
import numpy as np
import pandas as pd
from sklearn import linear_model

cv=pd.read_csv(r"casas-pro.csv",dtype="string")

cv['precio'] = cv['precio'].fillna('0')
cv['precio'] = cv['precio'].apply(lambda x: x.replace('$', '').replace(',', '').replace('MN','').replace(' ','')).astype(float)
cv['precio'] = cv['precio'].replace(0,np.NaN)
cv['mets'] = cv['mets'].fillna('0')
cv['mets'] = cv['mets'].astype(float)
cv['mets'] = cv['mets'].replace(0,np.NaN)
model=linear_model.LinearRegression()
depapre=pd.DataFrame(cv.loc[cv['web-scraper-start-url'].str.contains("mirador"),'precio'])
depamet=pd.DataFrame(cv.loc[cv['web-scraper-start-url'].str.contains("mirador"),'mets'])
#print(depapre)100% = 436 70% = 
depapre=depapre.iloc[0:305]
depamet=depamet.iloc[0:305]
#print(depapre)

model.fit(depamet,depapre)
model.predict(pd.DataFrame([120]))

         precio
36    3800000.0
188   1822842.0
195   2050000.0
224   2090000.0
316   2480000.0
...         ...
8583  2299000.0
8591  5000000.0
8593  2980000.0
8609  5000000.0
8622  2450000.0

[436 rows x 1 columns]


array([[2574685.115938]])

In [71]:
#30% test casas
import numpy as np
import pandas as pd
from sklearn import linear_model

cv=pd.read_csv(r"casas-pro.csv",dtype="string")

cv['precio'] = cv['precio'].fillna('0')
cv['precio'] = cv['precio'].apply(lambda x: x.replace('$', '').replace(',', '').replace('MN','').replace(' ','')).astype(float)
cv['precio'] = cv['precio'].replace(0,np.NaN)
cv['mets'] = cv['mets'].fillna('0')
cv['mets'] = cv['mets'].astype(float)
cv['mets'] = cv['mets'].replace(0,np.NaN)
model=linear_model.LinearRegression()
depapre=pd.DataFrame(cv.loc[cv['web-scraper-start-url'].str.contains("mirador"),'precio'])
depamet=pd.DataFrame(cv.loc[cv['web-scraper-start-url'].str.contains("mirador"),'mets'])
#print(depapre)100% = 73 70% = 51
depapre=depapre.iloc[305:]
depamet=depamet.iloc[305:]
#print(depapre)

model.fit(depamet,depapre)
model.predict(pd.DataFrame([120]))

array([[2185509.14762528]])