In [90]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0])

b = np.zeros(2)
print(b)

c = np.ones(2)
print(c)

d = np.empty(2)
print(d)

e = np.arange(6)
print(e)

f = np.arange(2,15,2)
print(f)

g = np.linspace(1,15,4)
print(g)

c = np.ones(4, dtype=int)
print(c)

m = np.append(c,[5,3])
print(m)

u = np.delete(e,[2,3])
print(u)

x = np.array([8,1,4,2,9,5])
print(x)
x = np.sort(x)
print(x)


j = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[8, 9, 10, 11],[12, 13, 14, 15]],[[16 ,17 ,18, 19],[20, 21, 22, 23]]])
print(j.ndim)
print(j.size)
print(j.shape)

x = e.reshape(3,2)
print(x)

y = np.array([1,2,3,4,5,6,7,8,9])
print(y.shape)

y2 = y[np.newaxis]
print(y2.shape)

y2 = y[:,np.newaxis]
print(y2.shape)

y2 = y[np.newaxis,:]
print(y2.shape)

y3 = np.expand_dims(y,axis=0)
print(y3.shape)

print(y[0])
print(y[0:2])
print(y[2:])
print(y[:-3])

print(y[y<3])
print(y[y>=3])
print(y[y%2==0])
print(y[(y>3) & (y<8)])
print((y>3) | (y<8))

l = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
l = np.where(l<5)
print(l)

p = list(zip(l[0],l[1]))
for cord in p:
    print(cord)
    

a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

x1 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(np.hsplit(x1,5))
print(np.hsplit(x1,(3,4)))

print(e.sum())
print(x1.sum(axis = 0))
print(e*2)
print(e.min())
print(e.max())

b1 = np.array([[1,2,3,4],[5,6,7,8]])
b2 = np.array([[1,2,3,4],[5,6,7,8]])

b3=(b1+b2)
print(b3)

[1 2 3 4]
[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3 4 5]
[ 2  4  6  8 10 12 14]
[ 1.          5.66666667 10.33333333 15.        ]
[1 1 1 1]
[1 1 1 1 5 3]
[0 1 4 5]
[8 1 4 2 9 5]
[1 2 4 5 8 9]
3
24
(3, 2, 4)
[[0 1]
 [2 3]
 [4 5]]
(9,)
(1, 9)
(9, 1)
(1, 9)
(1, 9)
1
[1 2]
[3 4 5 6 7 8 9]
[1 2 3 4 5 6]
[1 2]
[3 4 5 6 7 8 9]
[2 4 6 8]
[4 5 6 7]
[ True  True  True  True  True  True  True  True  True]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(0, 0)
(0, 1)
(0, 2)
(0, 3)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[array([[ 1,  2],
       [11, 12]]), array([[ 3,  4],
       [13, 14]]), array([[ 5,  6],
       [15, 16]]), array([[ 7,  8],
       [17, 18]]), array([[ 9, 10],
       [19, 20]])]
[array([[ 1,  2,  3],
       [11, 12, 13]]), array([[ 4],
       [14]]), array([[ 5,  6,  7,  8,  9, 10],
       [15, 16, 17, 18, 19, 20]])]
15
[12 14 16 18 20 22 24 26 28 30]
[ 0  2  4  6  8 10]
0
5
[[ 2  4  6  8]
 [10 12 14 16]]
